default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    # Setup
    setup_ci
    increment_build_number(xcodeproj: "sweather-2.xcodeproj")
    
    # Create our required config.xcconfig file
    File.open("../sweather-2/Build Config/config.xcconfig", "w+") { |file| 
    file.write("WILLY_WEATHER_API_KEY = #{ENV["WILLY_WEATHER_API_KEY"]}\n")
      file.write("GOOGLE_API_KEY = #{ENV["GOOGLE_API_KEY"]}\n")
    }

    # Setup certificates
    match(
      type: "appstore", 
      readonly: is_ci, 
      git_basic_authorization: ENV["GH_PERSONAL_ACCESS_TOKEN"],
      app_identifier: [
        "com.sjd.sweather",
        "com.sjd.sweather.SweatherWidget",
      ]
    )

    # Install pods
    cocoapods

    # Build
    build_app(
      workspace: "sweather-2.xcworkspace", 
      scheme: "sweather-2"
    )

    # Upload to testflight and submit for beta app review
    upload_to_testflight(
      beta_app_review_info: {
        contact_email: "sam@sjd.co",
        contact_first_name: "Sam",
        contact_last_name: "Davis",
        contact_phone: "+61487131311",
        notes: "This app is only designed for use within Australia."
      }
    )

    # Bump the version number, commit and re push to origin
    commit_version_bump(xcodeproj: "sweather-2.xcodeproj")
    add_git_tag
    push_to_git_remote

  end

  lane :screenshots do 
    capture_screenshots(clean: true)
  end

  lane :deliver_screenshots do
    deliver(
      app_version: "2.1",
      skip_binary_upload: true,
      skip_metadata: true,
      skip_screenshots: false,
      overwrite_screenshots: true,
      force: true
    )
  end
  
  lane :deliver_metadata do
    deliver(
      skip_binary_upload: true,
      skip_metadata: false,
      skip_screenshots: true,
      force: true
    )
  end
  
  lane :deliver_screenshots_and_metadata do
    deliver(
      skip_binary_upload: true,
      overwrite_screenshots: true,
      force: true
    )
  end

  lane :certificates do
    match(app_identifier: [
      "com.sjd.sweather",
      "com.sjd.sweather.SweatherWidget",
    ])
  end

end
