name: Build and distribute to TestFlight

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      env:
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLEID_APP_SPECIFIC_PW }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        WILLY_WEATHER_API_KEY: ${{ secrets.WILLY_WEATHER_API_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      with:
        lane: beta
